### ISSUE TITLE
Async APIs is missing examples for the parameters

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/docs#11]
## Expected content
1. `"customEntities": [{"entityName": "entityValue"}]`

2. `trackers = [{
    "name": "COVID-19",
    "vocabulary": [
      "social distancing",
      "cover your face with mask",
      "vaccination"
    ]
  }]`

## Actual content
![image](https://user-images.githubusercontent.com/67150433/121709406-25ceaf80-caf6-11eb-9fb4-7a4d83791b04.png)

customEntities example is not given in Async APIs
trackers example is not given in Async APIs

**Link to page**:

**Comment by pema-s** [comment]
The customEntities and Trackers examples are given in the sample code:

https://docs.symbl.ai/docs/async-api/overview/text/post-text#code-example

https://docs.symbl.ai/docs/async-api/overview/audio/post-audio-url#code-example

https://docs.symbl.ai/docs/async-api/overview/video/post-video-url#code-example

@harpreetvishnoi

**Comment by harpreetvishnoi** [comment]
Resolving this. Since trackers hyperlink is introduced and for customEntities we have another ticket
