### ISSUE TITLE
 enableSpeakerDiarization & diarizationSpeakerCount 

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/docs#13]
## Expected content
For our Async URL APIs (Audio & Video) enableSpeakerDiarization & diarizationSpeakerCount should ideally be passed in request body.

Also, for Async File (Audio & Video ) enableSpeakerDiarization & diarizationSpeakerCount should be passed in Query Parameter. We should include them in the main parameter list. Right now, we have 2 separate list due to which people think it is separate. All Query Parameters should be listed at one place. 

![image](https://user-images.githubusercontent.com/67150433/121722292-e3f83600-cb02-11eb-833f-f50ec56473fe.png)

## Actual content

Write now Query parameter is written on all of them. 

**Link to page**:

**Comment by pema-s** [comment]
This has been fixed on all Async API pages @harpreetvishnoi
