### ISSUE TITLE
Code example parameter name incorrect

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/docs#15]
## Expected content
code example should have: 

`{
  "languages": ["ja-JP"]
}`

## Actual content
![image](https://user-images.githubusercontent.com/67150433/121886128-abd73a00-cd32-11eb-9822-a6bad155d759.png)

https://docs.symbl.ai/docs/telephony-api/api-reference#supported-languages

**Link to page**:

**Comment by pema-s** [comment]
This has been updated @harpreetvishnoi
