### ISSUE TITLE
confidenceThreshold  =< 0.5 <=1.0.

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/docs#16]
## Expected content
 Confidence threshold should should =< 0.5 <=1.0.  in the documentation. Basically, it can be 0.5 or bigger and less than or equal to 1.0. 

Note @Pema if you try to put 0.3 it will tell you to increase it <=0.5 to <=1.0
In all APIs. 

## Actual content

![image](https://user-images.githubusercontent.com/67150433/121914143-a20fff80-cd4f-11eb-87cc-c7e6468e0751.png)

**Link to page**:

**Comment by HuckMatt** [comment]
@pemasp can we have this updated?  A couple of people have reached out regarding this discrepancy to support.

**Comment by pema-s** [comment]
The changes have been updated @HuckMatt @harpreetvishnoi
