### ISSUE TITLE
Update Trackers API (GET /mangage/trackers)

### ISSUE THREAD

**Issue by moona3k** [symblai/docs#2]
There is a missing segment in the documentation for the `GET Tracker` section.

`GET Tracker` should describe:
1) How to get an individual tracker (ie. `GET /manage/tracker/:id`)
> This is included already.
2) How to get all trackers (ie. `GET /manage/trackers`)
> This needs to be added in. I have confirmed on Postman that 'get all trackers' is active.

![Screen Shot 2021-06-04 at 2 58 53 PM](https://user-images.githubusercontent.com/32221114/120867206-5175f680-c546-11eb-8530-be31aaa04c20.png)

**Comment by pema-s** [comment]
Hi @moona3k 

Thanks for your suggestion. 

This request has been added to the docs. 

https://docs.symbl.ai/docs/management-api/trackers/get-tracker/#get-all-trackers
