### ISSUE TITLE
Remove examples from Action Items

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/docs#25]
Please remove these(2 marked in the image below) examples from the Action Items concept pages and add new examples at their place. 

Why remove the currently marked example? Ans: They don't work as Action Items now. 

Why add new examples in its place? Ans: So, the customers have wide range of examples to understand.   

![image](https://user-images.githubusercontent.com/67150433/122385244-2ea60200-cf8a-11eb-80c1-7d7f15a6a11b.png)

**Link to page**:

**Comment by pema-s** [comment]
Hi @harpreetvishnoi 

The two examples have been removed. 

Thanks for helping make our docs better!
