### ISSUE TITLE
Tidy up endpoint URL (GET Tracker)

### ISSUE THREAD

**Issue by moona3k** [symblai/docs#3]
There is a superfluous `&` character that should be removed.
Link - https://docs.symbl.ai/docs/management-api/trackers/get-tracker
Before - `GET https://api.symbl.ai/v1/manage/trackers?&name={trackerName}`
After - `GET https://api.symbl.ai/v1/manage/trackers?name={trackerName}`

Both path strings work fine, but the endpoint description should be tidy.

![Screen Shot 2021-06-04 at 4 39 38 PM](https://user-images.githubusercontent.com/32221114/120872979-2ba41e00-c555-11eb-89ab-fb1eae677eaa.png)

**Comment by pema-s** [comment]
Hi @moona3k 

Thanks for flagging this!

Have removed the extra character from the API endpoint.
