### ISSUE TITLE
`speechRecognition` description is incorrect. 

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/docs#33]
## Actual content
The description for this incorrect. We wrote speaker object definition in it. 

![image](https://user-images.githubusercontent.com/67150433/122844854-29490e80-d320-11eb-85d0-157ebb56b8a9.png)

**Link to page**:
https://docs.symbl.ai/docs/streaming-api/api-reference#config

**Comment by pema-s** [comment]
Hi @harpreetvishnoi 

Thanks for flagging this. 

The description has been corrected. 

Thanks again for helping make our docs better!
