### ISSUE TITLE
Issues in sample codes of Audio API- Python SDK

### ISSUE THREAD

**Issue by roshanijawale** [symblai/docs#43]
Ref : https://docs.symbl.ai/docs/python-sdk/async-audio

in this page

In sample code of Async Audio API and Appending Audio URL API including comment section, we are accessing functions of Conversation class without `get_` prefix.(expected `get_topics()` etc)

  2. we haven't included  `conversation_id` into append Audio API's code.

**Comment by pema-s** [comment]
Hi @roshanijawale,

Thanks for flagging this. 

The changes you pointed out has been added to the[ Async Audio API page for Python SDK](https://docs.symbl.ai/docs/python-sdk/async-audio). 

Thanks again for helping make our docs better!
