### ISSUE TITLE
Change the length for Async Time

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/docs#49]
## Expected content
As of this writing, the API accepts files that are 4 hours or less in duration.

## Actual content
As of this writing, the API accepts files that are 2 hours or less in duration.

**Link to page**:

https://docs.symbl.ai/docs/faq#what-is-the-maximum-length-of-meeting-duration-the-async-api-support

**Comment by pema-s** [comment]
This info has been updated. 

Thanks for flagging this.

@harpreetvishnoi
